
export const GlobalCommand={
    "GLOBAL_STAT":"GLOBAL_STAT",
    "OPEN_DOWNLOAD":"OPEN_DOWNLOAD",
    "CLOSE_DOWNLOAD":"CLOSE_DOWNLOAD",
    "OPEN_WAIT_DOWNLOAD":"OPEN_WAIT_DOWNLOAD",
    "CLOSE_WAIT_DOWNLOAD":"CLOSE_WAIT_DOWNLOAD",
    "OPEN_FINISH_DOWNLOAD":"OPEN_FINISH_DOWNLOAD",
    "CLOSE_FINISH_DOWNLOAD":"CLOSE_FINISH_DOWNLOAD"
};
