export const RpcWSCommand={
    'GLOBAL_STAT':'GLOBAL_STAT',
    'DOWNLOAD_STATS':'DOWNLOAD_STATS',
    "WAIT_DOWNLOAD_STATS":"WAIT_DOWNLOAD_STATS",
    "FINISH_DOWNLOAD_STATS":"FINISH_DOWNLOAD_STATS",


    "GLOBAL_OPTION_STAT":"GLOBAL_OPTION_STAT",
    "ROMOVE_COMMAND_JOB":"ROMOVE_COMMAND_JOB",
    "ADD_COMMAND_JOB":"ADD_COMMAND_JOB"
};

