export const RpcWSCommand={
    'GLOBAL_STAT':'GLOBAL_STAT',
    'DOWNLOAD_STATS':'DOWNLOAD_STATS',
    "WAIT_DOWNLOAD_STATS":"WAIT_DOWNLOAD_STATS",
    "FINISH_DOWNLOAD_STATS":"FINISH_DOWNLOAD_STATS",

    "ADD_URL":"ADD_URL",
    "ADD_TORRENT":"ADD_TORRENT",
    "ADD_METALINK":"ADD_METALINK",
    "FORCE_REMOVE":"FORCE_REMOVE",
    "REMOVE_DOWNLOAD_RESULT": "REMOVE_DOWNLOAD_RESULT",

    "Add_DOWNLOAD_ERROR":"Add_DOWNLOAD_ERROR",
    "REMOVE_DOWNLOAD_ERROR":"REMOVE_DOWNLOAD_ERROR",
    "PAUSE":"PAUSE",
    "UNPAUSE":"UNPAUSE",

    "GLOBAL_OPTION_STAT":"GLOBAL_OPTION_STAT",
    "UPDATE_GLOBAL_OPTION_STAT":"UPDATE_GLOBAL_OPTION_STAT",


    "ROMOVE_COMMAND_JOB":"ROMOVE_COMMAND_JOB",
    "ADD_COMMAND_JOB":"ADD_COMMAND_JOB"
};

