export const RpcWSCommand={
    'GLOBAL_STAT':'GLOBAL_STAT',
    'DOWNLOAD_STATS':'DOWNLOAD_STATS',
    "WAIT_DOWNLOAD_STATS":"WAIT_DOWNLOAD_STATS",
    "FINISH_DOWNLOAD_STATS":"FINISH_DOWNLOAD_STATS",
};

